ConsultaProdutos/ConsultaProdutos.MVC/Models/Produto.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ConsultaProdutos.MVC.Models
{
    public class Produto
    {
        public int ProdutoId { get; set; }

        public String Nome { get; set; }
        
        public Decimal Preco { get; set; }

        public String NomeMarca { get; set; }

        public int MarcaId { get; set; }
    }
}

ConsultaProdutos/ConsultaProdutos.MVC/Controllers/ProdutoController.cs
using ConsultaProdutos.MVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ConsultaProdutos.MVC.Controllers
{
    public class ProdutoController : Controller
    {
        static HttpClient httpClient;
        static readonly String endPointHeader = "application/json";
        static readonly String endPoint = "http://localhost:51115/";
        
        public ActionResult Index()
        {
            return View();
        }
        
        public async Task<JsonResult> Lista()
        {
            var rota = "Produto/ListarProdutosInicial";
            List<Produto> produtos = await ObterDadosProdutos(rota);
            
            return Json(produtos, JsonRequestBehavior.AllowGet);
        }

        private static async Task<List<Produto>> ObterDadosProdutos(string rota)
        {
            var produtosJson = string.Empty;
            List<Produto> produtos = null;
            ConfigurarHttpClient();

            HttpResponseMessage resposta = await httpClient.GetAsync(rota);

            if (resposta.IsSuccessStatusCode)
            {
                produtosJson = await resposta.Content.ReadAsStringAsync();
                produtos = JsonConvert.DeserializeObject<List<Produto>>(produtosJson);
            }

            FecharHttpClient();
            return produtos;
        }

        private static void ConfigurarHttpClient()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri(endPoint);
            httpClient.DefaultRequestHeaders.Accept.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(endPointHeader));
        }

        private static void FecharHttpClient()
        {
            httpClient = new HttpClient();
        }
    }
}

ConsultaProdutos/ConsultaProdutos.MVC/Views/Produto/Index.cshtml
@{
    ViewBag.Title = "Buscar produtos";
}

<div ng-app="ProdutoApp" ng-controller="produtoController">
    <div>
        <h2>Busca de Produtos</h2>
    </div>
    <div>
        <input type="text" class="form-control" name="nomeproduto" id="nomeproduto"
               placeholder="Digite aqui o nome do produto desejado" ng-model="nomeproduto" ng-keyup="Buscar()" />
    </div>
    <div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                    <th>Marca</th>
                </tr>
            </thead>
            <tbody ng-repeat="produto in produtos">
                <tr>
                    <td>{{produto.ProdutoId}}</td>
                    <td>{{produto.Nome}}</td>
                    <td>{{produto.Preco | currency:"R$ "}}</td>
                    <td>{{produto.NomeMarca}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<script src="~/Scripts/angular.js"></script>
<script src="~/Scripts/i18n/angular-locale_pt-br.js"></script>
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/App/produtoApp.js"></script>
<script src="~/Scripts/App/produtoFactory.js"></script>
<script src="~/Scripts/App/produtoController.js"></script>

ConsultaProdutos/ConsultaProdutos.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema de Consulta de Produtos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema de Consulta de Produtos", "Index", "Produto", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema de Consulta de Produtos</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>